[www]
user = nobody
group = nobody

; CRITICAL: Listen on TCP 9000 for cross-container FastCGI (NGINX will connect here)
listen = 9000

listen.owner = nobody
listen.group = nobody

pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; Required to allow environment variables to be passed to PHP workers
clear_env = no